### ISSUE TITLE
Package fails to load depending on installation

### ISSUE THREAD

**Issue by LaurentTreguier** [skandasoft/preview-plus#11]
I recently tried to install 'preview-plus' package for Atom. The package activates and works successfully when running `git clone https://github.com/skandasoft/preview-plus` and `apm install`. But when installing it through the settings panel of Atom, or using `apm install preview-plus`, the package can't be loaded and I find the following warnings in the console:
```
Failed to load package named 'preview-plus' Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/laurent/.atom/packages/preview-plus/lib/watch.coffee:2:13)
  at Object.<anonymous> (/home/laurent/.atom/packages/preview-plus/lib/watch.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:67:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/laurent/.atom/packages/preview-plus/lib/preview-plus.coffee:10:9)
  at Object.<anonymous> (/home/laurent/.atom/packages/preview-plus/lib/preview-plus.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:67:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:653:34)
  at /usr/share/atom/resources/app/src/package.js:190:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:378:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app/src/package-manager.js:355:14)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:617:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:52:25)

/usr/share/atom/resources/app/src/package.js:243 Failed to activate package named 'preview-plus' Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/laurent/.atom/packages/preview-plus/lib/watch.coffee:2:13)
  at Object.<anonymous> (/home/laurent/.atom/packages/preview-plus/lib/watch.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:67:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/laurent/.atom/packages/preview-plus/lib/preview-plus.coffee:10:9)
  at Object.<anonymous> (/home/laurent/.atom/packages/preview-plus/lib/preview-plus.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:67:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:653:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app/src/package.js:253:12)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:232:14)
  at /usr/share/atom/resources/app/src/package.js:221:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:464:21)
  at /usr/share/atom/resources/app/src/package-manager.js:445:29
  at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:350:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:439:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:422:46)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:620:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:52:25)
```
When looking at package.json in the package source code, the `event-kit` dependency seems to have disappeared from the `dependencies` list, even though it should be there... I've never had this problem until now; is it a problem with this package or with apm automated install ? Or with me, but I think I've done nothing wrong installing the package...

**Comment by skandasoft** [comment]
Thanks for checking..I think there was a patch @olmokramer ..I guess it didn't fix it.. I am currently working on a updated version ..so it might be another week before the new release..

**Comment by olmokramer** [comment]
@skandasoft I see (from the [commit history](https://github.com/skandasoft/preview-plus/commits/master)) that you didn't publish a new version with the patch I submitted.

**Comment by skandasoft** [comment]
updated with the new release. Please try. Thanks @olmokramer

**Comment by olmokramer** [comment]
Thanks! I'll try soon

**Comment by AnbuKakashi** [comment]
i cannot install it through apm 
i type apm install prewiev-plus@1.1.19
i get request for package information failed: not found..
what to do ?

**Comment by olmokramer** [comment]
What if you omit the version number? `apm install preview-plus`

**Comment by AnbuKakashi** [comment]
i have tried many times with or without numbers...
it doesnt work when installed thru settings so i wanted to try this way
its the same thing always as ive writen above, not found

**Comment by AnbuKakashi** [comment]
its was my error i was tying prewiev....it looks like its installing

**Comment by olmokramer** [comment]
Haha, stupid typos. Good to hear you fixed it :-)

**Comment by AnbuKakashi** [comment]
yeah i just hope itll work, im starting atom right now, as it does not work when installed thru settings :)

**Comment by AnbuKakashi** [comment]
it just wont work idk should i reinstall atom or what... there is no preview button in status bar or compile and when i go ctrl-shift-p and type config there is no config for preview-live only application: open your config...

**Comment by olmokramer** [comment]
There's an issue with the package, it doesn't list a dependency. I posted a solution in one of the issues here. Can't search for it right now

**Comment by AnbuKakashi** [comment]
thank you for your reply, do i need to have installed node.js for this package to work?

i dont think i have the skill to fix stuff within the atom itself  without detailed guide :(

**Comment by olmokramer** [comment]
No atom comes work its own version of node. If you have git installed, you can remove the package from your .atom/packages  folder, then come this repository into that folder and then run `apm install` from `~/.atom/packages/preview-plus`

**Comment by AnbuKakashi** [comment]
i have installed git and deleted the package from atom. Now about this next step im not quite sure what to do. Since i didnt use git i started to learn git wit try git form their page. Im also not sure did i make the right choices about instalation. I seleceted the git bash for commands not the cmd. 
Im sorry for bothering you...noobs are a pain more often then not :/

**Comment by olmokramer** [comment]
I'm sorry, I'm on mobile and autocorrect did changed "clone"  to "come"... 

Anyway, from a terminal/cmd do the following:

* `cd ~/.atom/packages`
* `git clone https://github.com/skandasoft/preview-plus`
* `cd preview-plus`
* `apm install`

I don't know if windows recognizes  `~` as your home directory, or what the windows equivalent is of the home directory.

And maybe you need to put the full path to the git executable in the git clone command, if it is not in your path.

**Comment by AnbuKakashi** [comment]
there were some thing that i needed to to to finish those commands but i did it, now just lets hope it works, its my only hope of learning jade the way i would like to do it.
if it doesnt work, ill reinstall atom and try for the last time then i give up

**Comment by skandasoft** [comment]
@AnbuKakashi I am the author here. I am currently half way between the release. I am unable to make the fix. You may have to wait for some time before I push the new release..

**Comment by AnbuKakashi** [comment]
i know and i thank you for this wonderfull package, ive even sent you a pm on yt asking for help.
now coudl you check out this for me:
http://i1369.photobucket.com/albums/ag216/Zethorium/Screenshot_2_zpsexphvmxs.png
i got that error am i missing smthn?

**Comment by skandasoft** [comment]
SASS preview needs the rubygems. gem install sass2css.

**Comment by AnbuKakashi** [comment]
how do i do that, do i need the full ruby install on windows, do i install that thru terminal?
sry about the stupid questions :$

**Comment by skandasoft** [comment]
yes I think you might have to install ruby on windows. and followed by gem install sass
check this out for Stylus ...http://learnboost.github.io/stylus/

**Comment by AnbuKakashi** [comment]
i didnt try jade to html whic is one of the main reasons i wanted this package, but will let you know once im done setting the css lol, btw ill take your advice on stylus

**Comment by AnbuKakashi** [comment]
ok so it too kme some time but i installed the stylus, and it works, im not tho sureabout those comiling when how why etc but that on other ocasion
i will now check jade and let u know does it work

**Comment by AnbuKakashi** [comment]
So the jade works just fine,but one thing that would be very convninet is to be able to save preview files as separate files, since browsers cant read jade.  Since it is showing in split pane, im aware it might not be done. ill look a way around it.

**Comment by olmokramer** [comment]
Hey, glad to hear you got it working. If you focus the preview, i.e. click on the text editor that's displaying the compiled html, you should be able to just <kbd>Ctrl+Shift+S</kbd> to "save as..."

**Comment by AnbuKakashi** [comment]
that is also working which is absolutely great :D 

thank you both for putting  up with me and helping me resolve this, sorry for spamming the comments

**Comment by AnbuKakashi** [comment]
I think i have found the best solution for jade and stylus and atom all together with my limited knowledge. I installed node.js and jade and stylus through npm. Now i keep 2 terminals active that monitor .jade and .stylus files and whenever i save update .html and .css files. Those files i can keep open in browser and just refresh it to see the changes. Someone also suggested me grunt but i didnt know anything about it and it includes js that i have not yet started learning. But the preview package allows me to see what im doing and have working files at the same time.

**Comment by skandasoft** [comment]
The package.json is updated..Check the latest Version
