### ISSUE TITLE
Failed to load the preview-plus package

### ISSUE THREAD

**Issue by thomasehardt** [skandasoft/preview-plus#12]
1. install following instructions from here: https://atom.io/packages/preview-plus#install
2. launch Atom

Fedora 21

**Atom Version**: 0.187.0
**System**: linux 3.17.4-301.fc21.x86_64
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.1.19

### Stack Trace

Failed to load the preview-plus package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/home/tehardt/.atom/packages/preview-plus/lib/watch.coffee:6:13)
    at Object.<anonymous> (/home/tehardt/.atom/packages/preview-plus/lib/watch.coffee:40:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
preview-plus, v1.1.19

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
updated with the new release. Please try

**Comment by thomasehardt** [comment]
I installed v1.1.20 and this error is gone but now I am getting cannot find module 'lodash' - will open a new ticket for that

**Comment by skandasoft** [comment]
The package.json is updated..Check the latest Version
