### ISSUE TITLE
Still no joy I'm afraid - Failed to load the preview-plus package

### ISSUE THREAD

**Issue by HumidBrains** [skandasoft/preview-plus#14]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.1.19

### Stack Trace

Failed to load the preview-plus package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/Jimmy/.atom/packages/preview-plus/lib/watch.coffee:2:13)
  at Object.<anonymous> (/Users/Jimmy/.atom/packages/preview-plus/lib/watch.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/Jimmy/.atom/packages/preview-plus/lib/preview-plus.coffee:10:9)
  at Object.<anonymous> (/Users/Jimmy/.atom/packages/preview-plus/lib/preview-plus.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:672:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:30)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -0:39.7 settings-view:open (atom-text-editor.editor)
     -0:28.6 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "dark-flat-ui",
      "outlander-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
ScssBundle, v0.4.0
color-picker, v1.4.4
css-comb, v2.0.1
css-snippets, v0.5.0
dark-flat-ui, v1.0.0
emmet, v2.3.4
filetype-color, v0.1.4
language-SCSS, v0.2.0
linter, v0.12.0
linter-jscs, v1.9.0
linter-scss-lint, v0.0.14
minimap, v4.5.0
minimap-color-highlight, v4.1.0
outlander-syntax, v1.0.1
preview-plus, v1.1.19
project-manager, v1.15.5
sass-compiler, v0.4.0
svg-preview, v0.5.1
webbox-color, v0.5.6

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
Same here. @skandasoft, you should run `apm publish patch` from the package's directory to actually publish the changes.

If you go to the package's directory on your system - `cd ~/.atom/packages/preview-plus/` - and then run `npm install event-kit`, the package should activate. If you don't have `npm` installed, you can edit the package's `package.json`: add `,"event-kit": "~1.0.2"` to the `dependencies` and then run `apm install` from the package's directory.

**Comment by shadowbq** [comment]
@olmokramer thanks.. fix worked on linux build as well. 
```shell
cd ~/.atom/packages/preview-plus/ && npm install event-kit
```

**Comment by skandasoft** [comment]
The package.json is updated..Check the latest Version
