### ISSUE TITLE
Failed to load the preview-plus package

### ISSUE THREAD

**Issue by JefAlive** [skandasoft/preview-plus#17]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.1.19

### Stack Trace

Failed to load the preview-plus package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/jeferson/.atom/packages/preview-plus/lib/watch.coffee:2:13)
  at Object.<anonymous> (/home/jeferson/.atom/packages/preview-plus/lib/watch.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/jeferson/.atom/packages/preview-plus/lib/preview-plus.coffee:10:9)
  at Object.<anonymous> (/home/jeferson/.atom/packages/preview-plus/lib/preview-plus.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:672:34)
  at /usr/share/atom/resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:464:30)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -1:18.7 pane:reopen-closed-item (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -1:04.8 styleguide:show (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:40.6 window:toggle-dev-tools (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
monokai, v0.12.0
preview-plus, v1.1.19

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
The package.json is updated..Check the latest Version
