### ISSUE TITLE
Failed to load the preview-plus package

### ISSUE THREAD

**Issue by paravatee** [skandasoft/preview-plus#19]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.1.19

### Stack Trace

Failed to load the preview-plus package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-0.187.0\resources\app\src\module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\preview-plus\lib\watch.coffee:2:13)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\preview-plus\lib\watch.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (C:\Users\Administrator\AppData\Local\atom\app-0.187.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\preview-plus\lib\preview-plus.coffee:10:9)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\preview-plus\lib\preview-plus.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (C:\Users\Administrator\AppData\Local\atom\app-0.187.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:672:34)
  at C:\Users\Administrator\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:189:28
  at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.load (C:\Users\Administrator\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Administrator\AppData\Local\atom\app-0.187.0\resources\app\src\package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Administrator\AppData\Local\atom\app-0.187.0\resources\app\src\package-manager.js:464:30)
  at C:\Users\Administrator\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:268:29
  at exit (C:\Users\Administrator\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\Administrator\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
  2x -7:22.3 core:confirm (atom-text-editor.editor.mini)
     -4:11.5 editor:select-to-beginning-of-word (atom-text-editor.editor)
     -4:09.9 script:run (atom-text-editor.editor)
  4x -2:51.8 editor:select-to-beginning-of-word (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
preview-plus, v1.1.19
script, v2.18.0

# Dev
No dev packages
```

**Comment by paravatee** [comment]
i'm use in windows and how to????????????????

**Comment by skandasoft** [comment]
You can check the comments from @olmokramer  on the other issues..Hopefully I can get some time this weekend to fix and release..
