### ISSUE TITLE
Uncaught TypeError: Cannot read property 'projectState' of undefined

### ISSUE THREAD

**Issue by Trudko** [skandasoft/preview-plus#2]
[Enter steps to reproduce below:]

1. Open atom i think without any project / folder opened.

**Atom Version**: 0.175.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.1.6

### Stack Trace

Uncaught TypeError: Cannot read property 'projectState' of undefined

```
At /c:/Users/Peter/.atom/packages/preview-plus/lib/preview-plus.coffee:59

TypeError: Cannot read property 'projectState' of undefined
  at module.exports.updateProject (c:\Users\Peter\.atom\packages\preview-plus\lib\preview-plus.coffee:35:21)
  at Project.module.exports.Emitter.emit (c:\Users\Peter\AppData\Local\atom\app-0.175.0\resources\app\node_modules\emissary\lib\emitter.js:118:15)
  at Project.module.exports.Project.setPaths (c:\Users\Peter\AppData\Local\atom\app-0.175.0\resources\app\src\project.js:216:12)
  at Ipc.<anonymous> (c:\Users\Peter\AppData\Local\atom\app-0.175.0\resources\app\src\window-event-handler.js:38:25)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (c:\Users\Peter\AppData\Local\atom\app-0.175.0\resources\atom\renderer\api\lib\ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-plus",
      "linter",
      "symbols-view"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by skandasoft** [comment]
Fixes are in. Can you try the updated version.

**Comment by Trudko** [comment]
Yes it seems this has fixed it.
