### ISSUE TITLE
Failed to load the preview-plus package

### ISSUE THREAD

**Issue by akosarek** [skandasoft/preview-plus#20]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.1.19

### Stack Trace

Failed to load the preview-plus package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/webmaster/.atom/packages/preview-plus/lib/watch.coffee:2:13)
  at Object.<anonymous> (/Users/webmaster/.atom/packages/preview-plus/lib/watch.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/webmaster/.atom/packages/preview-plus/lib/preview-plus.coffee:10:9)
  at Object.<anonymous> (/Users/webmaster/.atom/packages/preview-plus/lib/preview-plus.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:672:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:30)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
  2x -5:14.3 core:backspace (atom-text-editor.editor)
  3x -5:13.0 markdown-preview:toggle (atom-text-editor.editor)
     -4:17.4 core:move-up (atom-text-editor.editor)
     -4:14.9 editor:move-to-first-character-of-line (atom-text-editor.editor)
     -4:14.6 core:move-down (atom-text-editor.editor)
  2x -4:14.1 editor:newline (atom-text-editor.editor)
     -4:13.5 core:move-up (atom-text-editor.editor)
     -4:10.2 editor:newline (atom-text-editor.editor)
  2x -4:05.0 core:move-right (atom-text-editor.editor)
     -4:04.5 editor:newline (atom-text-editor.editor)
  2x -3:58.5 markdown-preview:toggle (atom-text-editor.editor)
  3x -3:53.6 core:backspace (atom-text-editor.editor)
     -3:51.2 core:save (atom-text-editor.editor)
  5x -3:34.3 markdown-preview:toggle (atom-text-editor.editor)
     -3:14.0 core:backspace (atom-text-editor.editor.mini)
  2x -1:01.0 markdown-preview:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.15.0
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.6.0
color-picker, v1.4.4
linter, v0.12.0
preview-plus, v1.1.19
tree-ignore, v0.2.5

# Dev
No dev packages
```

**Comment by akosarek** [comment]
@olmokramer fix worked.

**Comment by skandasoft** [comment]
The package.json is updated..Check the latest Version
