### ISSUE TITLE
Failed to load the preview-plus package

### ISSUE THREAD

**Issue by fenque** [skandasoft/preview-plus#21]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Unknown Windows Version
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.1.19

### Stack Trace

Failed to load the preview-plus package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (C:\Users\drozd\AppData\Local\atom\app-0.187.0\resources\app\src\module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\drozd\.atom\packages\preview-plus\lib\watch.coffee:2:13)
  at Object.<anonymous> (C:\Users\drozd\.atom\packages\preview-plus\lib\watch.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (C:\Users\drozd\AppData\Local\atom\app-0.187.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\drozd\.atom\packages\preview-plus\lib\preview-plus.coffee:10:9)
  at Object.<anonymous> (C:\Users\drozd\.atom\packages\preview-plus\lib\preview-plus.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (C:\Users\drozd\AppData\Local\atom\app-0.187.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\drozd\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:672:34)
  at C:\Users\drozd\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:189:28
  at Package.module.exports.Package.measure (C:\Users\drozd\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.load (C:\Users\drozd\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\drozd\AppData\Local\atom\app-0.187.0\resources\app\src\package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\drozd\AppData\Local\atom\app-0.187.0\resources\app\src\package-manager.js:464:30)
  at C:\Users\drozd\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:268:29
  at exit (C:\Users\drozd\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\drozd\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\drozd\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
     -5:42.0 find-and-replace:show (atom-text-editor.editor)
     -5:41.6 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.mini)
  7x -5:38.5 core:backspace (atom-text-editor.editor.mini)
     -5:36.8 editor:consolidate-selections (atom-text-editor.editor.mini)
     -5:36.8 core:cancel (atom-text-editor.editor.mini)
     -5:34.2 editor:consolidate-selections (atom-text-editor.editor)
     -5:34.2 core:cancel (atom-text-editor.editor)
     -5:33.9 editor:consolidate-selections (atom-text-editor.editor)
     -5:33.9 core:cancel (atom-text-editor.editor)
     -5:32.8 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
  7x -5:30.3 core:backspace (atom-text-editor.editor.mini)
     -5:25.9 web-browser:toggle (atom-text-editor.editor)
     -4:23.2 atom-html-preview:toggle (atom-text-editor.editor)
     -3:00.7 preview:select-renderer (atom-text-editor.editor)
     -2:41.3 preview:toggle (atom-text-editor.editor)
  3x -2:37.0 core:backspace (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-browser-webview, v0.6.0
browser-refresh, v0.8.3
linter, v0.12.0
linter-csslint, v0.0.11
linter-jshint, v0.1.0
livereload, v0.2.0
local-server-express, v0.1.3
preview-plus, v1.1.19
web-browser, v1.4.2

# Dev
No dev packages
```

**Comment by fibric** [comment]
same on osx, same version of atom, same version of preview-plus

**Comment by wesleycoder** [comment]
+1 for this in Windows 7

**Comment by skandasoft** [comment]
The package.json is updated..Check the latest Version
