### ISSUE TITLE
Failed to load the preview-plus package

### ISSUE THREAD

**Issue by gisandforestry** [skandasoft/preview-plus#23]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.19.2-1-MANJARO
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.1.19

### Stack Trace

Failed to load the preview-plus package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/quercus/.atom/packages/preview-plus/lib/watch.coffee:2:13)
  at Object.<anonymous> (/home/quercus/.atom/packages/preview-plus/lib/watch.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/quercus/.atom/packages/preview-plus/lib/preview-plus.coffee:10:9)
  at Object.<anonymous> (/home/quercus/.atom/packages/preview-plus/lib/preview-plus.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:672:34)
  at /usr/share/atom/resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:464:30)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -2:10.4 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
markdown-format, v2.5.0
markdown-preview-plus, v1.3.0
markdown-scroll-sync, v0.3.2
markdown-table-formatter, v2.5.2
open-last-project, v0.3.5
preview-plus, v1.1.19
tidy-markdown, v0.1.1

# Dev
No dev packages
```

**Comment by JacopKane** [comment]
Same here
```
Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/furkantunali/.atom/packages/preview-plus/lib/watch.coffee:2:13)
  at Object.<anonymous> (/Users/furkantunali/.atom/packages/preview-plus/lib/watch.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/furkantunali/.atom/packages/preview-plus/lib/preview-plus.coffee:10:9)
  at Object.<anonymous> (/Users/furkantunali/.atom/packages/preview-plus/lib/preview-plus.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:678:34)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package-manager.js:460:30)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)
```

**Comment by MasterSieben** [comment]
and here!
1. ...
2. ...

**Atom Version**: 0.188.0
**System**: linux 3.16.0-23-generic
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.1.19

### Stack Trace

Failed to load the preview-plus package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/master/.atom/packages/preview-plus/lib/watch.coffee:2:13)
  at Object.<anonymous> (/home/master/.atom/packages/preview-plus/lib/watch.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/master/.atom/packages/preview-plus/lib/preview-plus.coffee:10:9)
  at Object.<anonymous> (/home/master/.atom/packages/preview-plus/lib/preview-plus.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:678:34)
  at /usr/share/atom/resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app/src/package-manager.js:355:14)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:622:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:51:25)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "yosemite-unity-ui",
      "easyballs-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ascii-codes, v0.3.3
autoclose-html, v0.15.0
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
autocomplete-snippets, v1.2.0
color-picker, v1.6.0
css-snippets, v0.5.0
csslint, v1.0.4
easyballs-theme, v0.5.0
editor-settings, v0.5.1
editor-stats, v0.17.0
emmet, v2.3.7
highlight-line, v0.10.1
html-entities, v0.3.1
html-helper, v0.2.3
javascript-snippets, v1.0.0
jshint, v1.3.1
nevish, v0.1.2
preview-plus, v1.1.19
project-manager, v1.15.5
python, v0.5.1
tag, v0.2.3
w3c-validation, v0.1.3
yosemite-unity-ui, v0.3.13

# Dev
No dev packages
```

**Comment by ashebanow** [comment]
ditto, on 0.192.0 mac/yosemite

**Comment by cog-piisang** [comment]
Same, 0.187.0 mac/yosemite

**Comment by adius** [comment]
+1

**Comment by iammarkoradak** [comment]
+1

**Comment by cog-piisang** [comment]
Workaround is simple:
`git clone git://github.com/atom/event-kit.git ~/.atom/packages/preview-plus/event-kit`
`cd ~/.atom/packages/preview-plus/event-kit && npm install`

**Comment by ymatuhin** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.1.19

### Stack Trace

Failed to load the preview-plus package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/ymatuhin/.atom/packages/preview-plus/lib/watch.coffee:2:13)
  at Object.<anonymous> (/Users/ymatuhin/.atom/packages/preview-plus/lib/watch.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/ymatuhin/.atom/packages/preview-plus/lib/preview-plus.coffee:10:9)
  at Object.<anonymous> (/Users/ymatuhin/.atom/packages/preview-plus/lib/preview-plus.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:677:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:161:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:354:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:433:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:276:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:85:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -0:09.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused)
     -0:08.4.0 core:undo (atom-text-editor.editor.is-focused)
     -0:07.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:07.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:07.5.0 core:undo (atom-text-editor.editor.is-focused)
     -0:06.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused)
     -0:06.0 core:undo (atom-text-editor.editor.is-focused)
     -0:05.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:05.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:04.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:04.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:03.9.0 core:undo (atom-text-editor.editor.is-focused)
     -0:02.4.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -0:01.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "code-links",
      "linter-tidy",
      "linter-coffeelint",
      "linter-stylint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
angularjs, v0.2.0
atom-beautify, v0.24.1
autocomplete-plus, v2.12.0
color-picker, v1.7.0
emmet, v2.3.8
file-icons, v1.5.4
linter, v0.12.1
linter-jshint, v0.1.2
minimap, v4.7.6
preview-plus, v1.1.19
project-manager, v1.15.5
project-palette-finder, v2.4.17

# Dev
No dev packages
```

**Comment by learningjs** [comment]
Good the @cog-piisang workaround, helps (clone event-kit to preview-plus/node_modules to make it work):
git clone git://github.com/atom/event-kit.git ~/.atom/packages/preview-plus/node_modules/event-kit

Then restart Atom :)

**Comment by skandasoft** [comment]
The package.json is updated..Check the latest Version
