### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by mgk22** [skandasoft/preview-plus#26]
[Enter steps to reproduce below:]

1. Create an HTML PAge
2. Se;ect "Live"

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.1.31

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/rjain/.atom/packages/preview-plus/lib/preview-plus.coffee:188

TypeError: Cannot read property 'replace' of undefined
  at Object.module.exports.preview (/Users/rjain/.atom/packages/preview-plus/lib/preview-plus.coffee:188:52)
  at Object.module.exports.toggle (/Users/rjain/.atom/packages/preview-plus/lib/preview-plus.coffee:170:10)
  at StatusView.toggleLive (/Users/rjain/.atom/packages/preview-plus/lib/status-view.coffee:135:14)
  at HTMLSpanElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:181:36)
  at HTMLSpanElement.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLSpanElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLSpanElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -0:14.5.0 grammar-selector:show (atom-text-editor.editor)
     -0:12.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.3.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor)
     -0:01.5.0 grammar-selector:show (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Sublime-Style-Column-Selection, v1.2.3
atom-alignment, v0.12.0
atom-jshint, v1.5.0
atom-typescript, v4.1.1
autocomplete-css, v0.6.0
autocomplete-html, v0.6.0
autocomplete-php, v0.2.5
autocomplete-plus, v2.12.1
autocomplete-plus-async, v0.22.0
autocomplete-ruby, v0.1.0
autocomplete-snippets, v1.3.0
browser-plus, v0.0.11
change-case, v0.5.1
color-picker, v1.7.0
css-snippets, v0.8.0
emmet, v2.3.8
jslint, v1.3.1
language-jsoniq, v1.3.0
linter, v0.12.1
linter-bootlint, v0.0.5
linter-coffeelint, v0.2.2
linter-eslint, v0.5.3
linter-javac, v0.1.3
linter-php, v0.0.12
linter-puppet-lint, v0.2.8
linter-pylint, v0.2.1
linter-rubocop, v0.2.3
linter-scss-lint, v0.0.14
linter-shellcheck, v0.0.7
linter-swiftc, v1.0.0
linter-tslint, v0.2.1
linter-xmllint, v0.0.5
minimap, v4.8.0
npm-autocomplete, v0.1.2
preview-plus, v1.1.31
seti-syntax, v0.4.0
seti-ui, v0.7.1
trailing-spaces, v0.2.5
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
fixed...with the latest update..please feel free to open if it is still a issue
