### ISSUE TITLE
'Failed to activate the preview-plus package' error

### ISSUE THREAD

**Issue by danielbayley** [skandasoft/preview-plus#32]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.2.2

### Stack Trace

Failed to activate the preview-plus package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at /Users/Dan/Library/Application Support/Atom/packages/preview-plus/lib/preview-plus.coffee:98:34
  at Function.find (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/lodash/dist/lodash.js:3217:15)
  at Object.module.exports.activate (/Users/Dan/Library/Application Support/Atom/packages/preview-plus/lib/preview-plus.coffee:96:21)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:313:19
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:142:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -4:55.5.0 core:save (atom-text-editor.editor.is-focused)
     -4:49.6.0 preview:toggle (atom-text-editor.editor.is-focused)
     -4:42.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -4:36.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:27.5.0 application:new-file (atom-text-editor#browser-plus.homepage.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".DS_Store",
      "._*",
      "Icon",
      ".git",
      "*.pyc",
      "*.rsrc",
      "*.webloc",
      "*.url"
    ],
    "followSymlinks": true,
    "disabledPackages": [
      "emmet",
      "autocomplete",
      "remember-session",
      "file-type-icons",
      "svg-preview",
      "red-wavy-underline",
      "color-gutter",
      "git-tab-status",
      "enhanced-package-list",
      "livereload",
      "word-count",
      "atom-color-highlight"
    ],
    "projectHome": "~/Library/Application Support/Atom/․atom/packages",
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "preview-plus": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
atom-html-preview, v0.1.10
autocomplete-paths, v1.0.2
browser-plus, v0.0.25
build, v0.41.0
change-case, v0.6.0
color-picker, v2.0.10
css-comb, v2.1.1
file-icons, v1.5.8
file-types, v0.4.1
gist-it, v0.7.0
jsonlint, v1.1.2
language-apache, v1.3.0
language-applescript, v0.2.0
language-svg, v0.8.0
language-swift, v0.4.0
language-yaml, v0.22.0
linter, v1.2.4
linter-coffeelint, v1.0.0
linter-csslint, v0.0.14
linter-htmlhint, v0.0.17
linter-js-yaml, v1.1.1
linter-jshint, v1.0.5
linter-less, v2.0.3
linter-perl, v0.6.1
linter-rubocop, v0.2.7
linter-scss-lint, v1.0.5
linter-shellcheck, v0.0.8
linter-xmllint, v0.0.7
open-recent, v2.3.0
pain-split, v1.4.0
preview, v0.16.3
preview-plus, v1.2.2
seti-syntax, v0.4.0
seti-ui, v0.7.1
takana-atom, v0.1.0
web-browser, v1.5.0
wordcount, v2.2.2

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
can you check the latest version.

**Comment by danielbayley** [comment]
Strange. I did still have the problem after updating within Atom, but I un/reinstalled it with `apm` and now no more error. I did get this little warning in Terminal however (altough probably unrelated);
```
[BABEL] Note: The code generator has deoptimised the styling of "/Users/Dan/Library/Application Support/Atom/packages/preview-plus/lib/resources/react.js" as it exceeds the max of "100KB".
```

**Comment by skandasoft** [comment]
good..I will close this ..working on rewrite of this to make it more modular/optimized..
