### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by davidpp** [skandasoft/preview-plus#34]
[Enter steps to reproduce below:]

1. Open coffeescript file
2. Show preview
3. Toggle Live Preview

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.2.3

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/davidpaquet/.atom/packages/preview-plus/lib/preview-plus.coffee:71

TypeError: undefined is not a function
  at /Users/davidpaquet/.atom/packages/preview-plus/lib/preview-plus.coffee:71:32
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Object.module.exports.toggleLive (/Users/davidpaquet/.atom/packages/preview-plus/lib/preview-plus.coffee:15:17)
  at atom-workspace.atom.commands.add.preview-plus:toggleLive (/Users/davidpaquet/.atom/packages/preview-plus/lib/preview-plus.coffee:87:72)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:22.6.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:22.3.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:21 command-palette:toggle (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  4x -0:17.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:14.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:11.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.6.0 preview-plus:preview (atom-text-editor.editor.vim-mode.insert-mode)
  3x -0:09.1.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:07.2.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
  3x -0:06.3.0 core:move-left (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:05.6.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:04.8.0 command-palette:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  4x -0:02.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:01.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.0 preview-plus:toggleLive (atom-text-editor.editor.vim-mode.insert-mode)
```

### Config

```json
{
  "core": {},
  "preview-plus": {
    "livePreview": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
formatter, v2.12.3
formatter-coffeescript, v0.1.1
linter, v1.2.4
linter-coffeelint, v1.0.0
linter-jsonlint, v0.1.4
preview-plus, v1.2.3
tabs-to-spaces, v0.11.0
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
fixed..please check the latest version
