### ISSUE TITLE
Uncaught TypeError: Cannot read property 'htmlu' of undefined

### ISSUE THREAD

**Issue by Norfeldt** [skandasoft/preview-plus#35]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Unknown Windows Version
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.2.5

### Stack Trace

Uncaught TypeError: Cannot read property 'htmlu' of undefined

```
At C:\Users\Norfeldt\.atom\packages\preview-plus\lib\status-view.coffee:111

TypeError: Cannot read property 'htmlu' of undefined
  at StatusView.compile (C:\Users\Norfeldt\.atom\packages\preview-plus\lib\status-view.coffee:111:38)
  at HTMLSpanElement.<anonymous> (C:\Users\Norfeldt\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:220:36)
  at HTMLSpanElement.jQuery.event.dispatch (C:\Users\Norfeldt\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLSpanElement.elemData.handle (C:\Users\Norfeldt\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -6:04.4.0 tree-view:toggle-focus (atom-pane.pane.active)
  4x -6:02.6.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -6:00.1.0 tree-view:toggle-focus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -5:58.3.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:37.6.0 settings-view:open (atom-pane.pane.active)
  2x -5:32.1.0 key-binding-resolver:toggle (div.settings-view.pane-item)
     -5:25.8.0 settings-view:open (div.settings-view.pane-item)
     -5:10.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:28.4.0 markdown-preview:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:59.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tidy-markdown",
      "markdown-preview-opener"
    ]
  },
  "preview-plus": {}
}
```

### Installed Packages

```coffee
# User
foldingtext-markdown, v1.3.2
preview-plus, v1.2.5

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
can you check the latest. Also could you try install browser-plus package(http://atom.io/packages/browser-plus)

**Comment by skandasoft** [comment]
assuming the issue is resolved...please feel free to reopen if it still a problem
