### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by smithjoelt** [skandasoft/preview-plus#36]
[Enter steps to reproduce below:]

1. ... Opened Browser-Plus window
2. ... Chose Jade for preview in Preview-Plus
 
**Atom Version**: 1.0.6
**System**: Ubuntu 14.04.3
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.2.6

### Stack Trace

Uncaught Error: spawn EACCES

```
At child_process.js:1145

Error: spawn EACCES
    at exports._errnoException (util.js:734:11)
    at ChildProcess.spawn (child_process.js:1145:11)
    at exports.spawn (child_process.js:977:9)
    at /home/arrogantprick/.atom/packages/preview-plus/lib/lang/html.coffee:57:16
    at /home/arrogantprick/.atom/packages/linter-haml/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
     -0:13.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:11.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.7.0 browser-plus:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-html-preview",
      "highlight-css-color",
      "welcome",
      "atom-html5-boilerplate",
      "auto-detect-indentation",
      "autoclose-html",
      "auto-indent",
      "language-mustache",
      "archive-view",
      "background-tips",
      "bookmarks",
      "go-to-line",
      "image-view",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-shellscript",
      "language-source",
      "language-sql",
      "language-todo",
      "language-toml",
      "link",
      "open-on-github",
      "styleguide",
      "timecop",
      "vim-surround",
      "vim-mode",
      "open-vim",
      "web-browser",
      "ruby-bundler",
      "ruby-test",
      "rails-transporter",
      "rails-snippets",
      "rails-rspec",
      "rails-partials",
      "linter-ruby",
      "linter-rubocop",
      "linter-erb"
    ],
    "themes": [
      "atom-material-ui",
      "AtomicSkittles"
    ],
    "autoHideMenuBar": true
  },
  "preview-plus": {
    "htmlp": true,
    "htmlu": true,
    "livePreview": true
  }
}
```

### Installed Packages

```coffee
# User
AtomicSkittles, v0.7.0
atom-jade, v0.3.0
atom-material-ui, v0.5.13
autocomplete-ruby, v0.1.0
browser-plus, v0.0.34
color-picker, v2.0.9
emmet, v2.3.12
file-icons, v1.6.3
html2haml, v0.10.0
jade-autocompile, v0.6.3
jshint, v1.3.10
language-haml, v0.21.0
linter, vundefined
linter-haml, v1.0.0
linter-jshint, v1.1.5
minimap, v4.12.2
minimap-git-diff, v4.1.7
preview-plus, v1.2.6

# Dev
No dev packages
```

**Comment by 0bserver07** [comment]
I'm getting a similar Error:

`'haml' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.`

```
Uncaught Error: 
write EPIPE
exports._errnoException @ util.js:837
exports._exceptionWithHostPort @ util.js:860afterWrite @ net.js:760
events.js:141 

Uncaught Error: spawn haml ENOENT
exports._errnoException @ util.js:837
ChildProcess._handle.onexit @ internal/child_process.js:178
onErrorNT @ internal/child_process.js:344
doNTCallback2 @ node.js:441
_tickCallback @ node.js:355
```

**Comment by skandasoft** [comment]
preview-plus - is deprecated..Please try pp(https://atom.io/packages/pp)
