### ISSUE TITLE
Uncaught TypeError: Cannot read property 'watch' of undefined

### ISSUE THREAD

**Issue by mhuggins7278** [skandasoft/preview-plus#37]
[Enter steps to reproduce below:]

Open a .jade file attempt to lauch preview-plus: base

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.3
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.2.6

### Stack Trace

Uncaught TypeError: Cannot read property 'watch' of undefined

```
At /Users/mark/.atom/packages/preview-plus/lib/htmlbase.coffee:10

TypeError: Cannot read property 'watch' of undefined
  at Function.module.exports.HTMLBase.content (/Users/mark/.atom/packages/preview-plus/lib/htmlbase.coffee:10:15)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:156:31)
  at Function.View.buildHtml (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:123:10)
  at HTMLBase.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:155:33)
  at new HTMLBase (/Users/mark/.atom/packages/preview-plus/lib/htmlbase.coffee:8:3)
  at Object.module.exports.base (/Users/mark/.atom/packages/preview-plus/lib/preview-plus.coffee:111:27)
  at atom-workspace.atom.commands.add.preview-plus:base (/Users/mark/.atom/packages/preview-plus/lib/preview-plus.coffee:85:66)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -2:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:01.3.0 preview:toggle (atom-text-editor.editor)
     -1:54.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:52.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:52 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:52 preview-plus:base (atom-text-editor.editor)
     -1:40.2.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:57.4.0 settings-view:open (atom-text-editor.editor.is-focused)
 12x -0:56.3.0 core:backspace (div.settings-view.pane-item)
     -0:08.8.0 git-history:show-file-history (atom-text-editor.editor.is-focused)
     -0:06.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:06.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:04.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 preview-plus:base (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "Thumbs.db",
      "bower_components",
      "node_modules"
    ]
  },
  "preview-plus": {
    "livePreview": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
color-picker, v2.0.11
column-select, v0.2.0
git-history, v3.0.0
git-log, v0.4.1
git-plus, v5.3.3
grunt-runner, v0.11.0
highlight-column, v0.5.0
language-SCSS, v0.4.0
language-javascript-jsx, v0.3.7
linter, v1.3.4
linter-coffeelint, v1.0.2
linter-jshint, v1.1.5
linter-jsxhint, v0.1.2
linter-python-pep8, v0.2.0
linter-scss-lint, v2.0.0
pain-split, v1.4.0
pretty-json, v0.4.1
preview, v0.16.3
preview-plus, v1.2.6
react, v0.12.6
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
preview-plus - is deprecated..Please try pp(https://atom.io/packages/pp)
