### ISSUE TITLE
Jade compile fails

### ISSUE THREAD

**Issue by olmokramer** [skandasoft/preview-plus#4]
Compilation of jade files fails on Atom 0.176.0 on Linux Debian 8 (testing)

I tried to compile this
```
ul.test
  li.item
  li.item
  li.item
#another-test
```
But the output shows this
```
undefined

undefined is not a function
```

**Comment by olmokramer** [comment]
There's a message logged in the console:
```
undefined is not a function
```
It gets logged in the catch statement on [line 158 in `preview-plus.coffee`](https://github.com/skandasoft/preview-plus/blob/master/lib/preview-plus.coffee#L158)

This is the stack trace:
```
TypeError: undefined is not a function
  at Object.<anonymous> (/home/olmo/.atom/packages/preview-plus/lib/lang/jade.coffee:3:19)
  at Object.<anonymous> (/home/olmo/.atom/packages/preview-plus/lib/lang/jade.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/atom/resources/app/src/coffee-cache.js:74:19)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.module.exports.toggle (/home/olmo/.atom/packages/preview-plus/lib/preview-plus.coffee:134:14)
  at atom-workspace.atom.commands.add.preview-plus:preview (/home/olmo/.atom/packages/preview-plus/lib/preview-plus.coffee:85:69)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:170:20)
```

**Comment by olmokramer** [comment]
`loophole.allowUnsafe` on [line 2 in `lib/lang/jade.coffee`](https://github.com/skandasoft/preview-plus/blob/master/lib/lang/jade.coffee#L2) doesn't exist according to this code I tested:
```
loophole = require 'loophole'
console.log loophole.allowUnsafe?
```

**Comment by olmokramer** [comment]
I tried from the command line:
```
$ coffee
> loophole = require 'loophole'
```
`loophole` had 4 methods: `allowUnsafeEval`, `allowUnsafeNewFunction`, `allowUnsafe` and `Function`

But when I edited `lib/lang/jade.coffee` to read
```
loophole = require 'loophole'
console.log loophole
```
`loophole` had just 2 methods: `allowUnsafeEval` and `allowUnsafeNewFunction`

**Comment by skandasoft** [comment]
Thanks for debugging. You solved the issue. I put a fix. Please test it.

Also I am not sure on how the ruby gem binary work in linux. If you have a chance, can you check under the spec/test list of test files for ruby slim files 1.slim --> to html 
or the scss or sass files..

**Comment by olmokramer** [comment]
Jade compile works! Thanks! I'll get back with the other results

**Comment by olmokramer** [comment]
The others fail with this error message:
```
'slimrb' (or 'sass') could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
```
But I guess that makes sense, because I don't have them installed...

**Comment by skandasoft** [comment]
I updated the jade to take the data while compiling..use the <pp-data> tag to pass the data. Only thing to take care is to put it in block comments..

Here is screen shot..

![jade](https://cloud.githubusercontent.com/assets/9875379/5994792/252a306c-aa47-11e4-9f98-46b25537458c.gif)

I am closing this for now.

**Comment by skandasoft** [comment]
ofcourse you might know that all the preview would do a selected preview..
![jade-select-preview](https://cloud.githubusercontent.com/assets/9875379/5994855/163042f2-aa49-11e4-87b6-15e19d742c98.gif)
