### ISSUE TITLE
Uncaught alert: Set the Grammar for the Editor

### ISSUE THREAD

**Issue by morozzoff** [skandasoft/preview-plus#41]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.2.6

### Stack Trace

Uncaught alert: Set the Grammar for the Editor

```
At /C:/Users/catson/.atom/packages/preview-plus/lib/preview-plus.coffee:460

Error
  at Object.<anonymous> (C:\Users\catson\.atom\packages\preview-plus\lib\preview-plus.coffee:7:25)
  at Object.<anonymous> (C:\Users\catson\.atom\packages\preview-plus\lib\preview-plus.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\catson\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\catson\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:761:34)
  at C:\Users\catson\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:192:28

```

### Commands

```
     -0:28.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:28.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:28.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:27.9.0 core:close (atom-text-editor.editor.is-focused)
     -0:20.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:17.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:16.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:16.2.0 preview-plus:toggleHTML (atom-text-editor.editor)
     -0:12.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  9x -0:10.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:06.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:06.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:05.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:03.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:02.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.4.0 preview-plus:toggleHTML (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "preview-plus": {
    "html": "browser",
    "css": "SCSS",
    "htmlu": true,
    "livePreview": true
  }
}
```

### Installed Packages

```coffee
# User
atom-slime, v1.7.2
color-picker, v2.0.13
emmet, v2.3.13
preview-plus, v1.2.6

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
preview-plus - is deprecated..Please try pp(https://atom.io/packages/pp)
