### ISSUE TITLE
Uncaught Error: ENAMETOOLONG: name too long, open '/Users/duanxudong/Java/preview~preview~preview...

### ISSUE THREAD

**Issue by drduan** [skandasoft/preview-plus#42]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.2.6

### Stack Trace

Uncaught Error: ENAMETOOLONG: name too long, open '/Users/duanxudong/Java/preview~preview~preview~preview~preview~preview~preview~preview~preview~preview~preview~preview~preview~Test.java.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:486

Error: ENAMETOOLONG: name too long, open '/Users/duanxudong/Java/preview~preview~preview~preview~preview~preview~preview~preview~preview~preview~preview~preview~preview~Test.java.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err.coffee.err'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Workspace.module.exports.Workspace.openTextFile (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:528:27)
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:461:23)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:393:19)
    at Object.module.exports.preview (/Users/duanxudong/.atom/packages/preview-plus/lib/preview-plus.coffee:216:22)
    at Object.module.exports.toggle (/Users/duanxudong/.atom/packages/preview-plus/lib/preview-plus.coffee:179:10)
    at /Users/duanxudong/.atom/packages/preview-plus/lib/status-view.coffee:104:16
```

### Commands

```
  4x -1:38.1.0 core:move-right (atom-text-editor.editor.power-mode.is-focused)
     -1:37.1.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -1:36.4.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
     -1:35.2.0 preview-plus:preview (atom-text-editor.editor.power-mode.is-focused)
     -1:30.9.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -1:26.4.0 core:cut (atom-text-editor.editor.power-mode.is-focused)
     -1:25.2.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -1:25.2.0 preview-plus:preview (atom-text-editor.editor.power-mode.is-focused)
     -1:21.8.0 core:move-down (atom-text-editor.editor.power-mode.is-focused)
  4x -1:20.3.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -1:19.4.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -1:18.9.0 preview-plus:preview (atom-text-editor.editor.power-mode.is-focused)
  7x -0:47.5.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
  7x -0:46.2.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
 23x -0:39.6.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -0:32.6.0 preview-plus:preview (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {},
  "preview-plus": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.4.1
preview-plus, v1.2.6
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
preview-plus - is deprecated..Please try pp(https://atom.io/packages/pp)
