### ISSUE TITLE
Uncaught TypeError: Cannot read property 'watch' of undefined

### ISSUE THREAD

**Issue by NyxCode** [skandasoft/preview-plus#43]
[Enter steps to reproduce below:]

1. Loading Preview Plus: base (Ctrl+shift+p)

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.2.6

### Stack Trace

Uncaught TypeError: Cannot read property 'watch' of undefined

```
At /C:/Users/Ded-Sec%20Mobile/.atom/packages/preview-plus/lib/htmlbase.coffee:20

TypeError: Cannot read property 'watch' of undefined
    at Function.module.exports.HTMLBase.content (file:///C:/Users/Ded-Sec Mobile/.atom/packages/preview-plus/lib/htmlbase.coffee:10:5)
    at Function.<anonymous> (C:\Users\Ded-Sec Mobile\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:156:31)
    at Function.View.buildHtml (C:\Users\Ded-Sec Mobile\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:123:10)
    at HTMLBase.View [as constructor] (C:\Users\Ded-Sec Mobile\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:155:33)
    at new HTMLBase (file:///C:/Users/Ded-Sec Mobile/.atom/packages/preview-plus/lib/htmlbase.coffee:8:3)
    at Object.module.exports.base (file:///C:/Users/Ded-Sec Mobile/.atom/packages/preview-plus/lib/preview-plus.coffee:111:27)
    at atom-workspace.atom.commands.add.preview-plus:base (file:///C:/Users/Ded-Sec Mobile/.atom/packages/preview-plus/lib/preview-plus.coffee:85:66)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Ded-Sec Mobile\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Ded-Sec Mobile\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Ded-Sec Mobile\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Ded-Sec Mobile\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\Ded-Sec Mobile\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Ded-Sec Mobile\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Ded-Sec Mobile\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Ded-Sec Mobile\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Ded-Sec Mobile\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Ded-Sec Mobile\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\Ded-Sec Mobile\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
  2x -1:49 core:move-right (atom-text-editor.editor.is-focused)
     -1:48 core:move-down (atom-text-editor.editor.is-focused)
     -1:47.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:47.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:47.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:47.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:46 preview-plus:preview (atom-text-editor.editor.is-focused)
     -1:45.2.0 core:undo (atom-text-editor.editor.is-focused)
     -1:44 preview-plus:preview (atom-text-editor.editor.is-focused)
  5x -1:38.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:36.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:35.3.0 preview-plus:preview (atom-text-editor.editor.is-focused)
     -0:06.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:04.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.7.0 preview-plus:base (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "openEmptyEditorOnStart": false
  },
  "preview-plus": {
    "livePreview": true,
    "htmlu": true
  }
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.54
icon-fonts, v1.10.0
preview-plus, v1.2.6
seti-icons, v0.4.5
seti-syntax, v0.4.1
seti-ui, v0.8.1

# Dev
No dev packages
```

**Comment by petonic** [comment]
+1

**Comment by nmaggioni** [comment]
+1

**Comment by shawnleong** [comment]
+1

**Comment by mehdifanai** [comment]
+1

**Comment by touhos** [comment]
+1

**Comment by skandasoft** [comment]
preview-plus - is deprecated..Please try pp(https://atom.io/packages/pp)
