### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by NataliaTepluhina** [skandasoft/preview-plus#46]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Unknown Windows Version
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.2.6

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /C:/Users/Zodiac/.atom/packages/preview-plus/lib/status-view.coffee:138

TypeError: Cannot read property 'getPath' of undefined
    at BrowserView.open (file:///C:/Users/Zodiac/.atom/packages/preview-plus/lib/status-view.coffee:68:19)
    at BrowserView.openChrome (file:///C:/Users/Zodiac/.atom/packages/preview-plus/lib/status-view.coffee:46:6)
    at HTMLSpanElement.<anonymous> (C:\Users\Zodiac\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:220:36)
    at HTMLSpanElement.jQuery.event.dispatch (C:\Users\Zodiac\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (C:\Users\Zodiac\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -1:27.4.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
  2x -0:36 core:delete (atom-text-editor.editor.is-focused)
     -0:29.7.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "navigate",
      "browser-plus"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.4.3
preview-plus, v1.2.6

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
preview-plus - is deprecated..Please try pp(https://atom.io/packages/pp)
