### ISSUE TITLE
Uncaught console: Error on line 142: Invalid US-ASCII character "\xC2"  Use --trace for backtrace.

### ISSUE THREAD

**Issue by lankford** [skandasoft/preview-plus#48]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [preview-plus](https://github.com/skandasoft/preview-plus) package, v1.2.6

### Stack Trace

Uncaught console: Error on line 142: Invalid US-ASCII character "\xC2"
  Use --trace for backtrace.

```
At /Users/mattlankford/.atom/packages/preview-plus/lib/preview-plus.coffee:168

console: Error on line 142: Invalid US-ASCII character "\xC2"
  Use --trace for backtrace.

    at Object.<anonymous> (/Users/mattlankford/.atom/packages/preview-plus/lib/preview-plus.coffee:165:19)
    at fire (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3099:30)
    at Object.self.fireWith [as rejectWith] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3211:7)
    at Object.deferred.(anonymous function) [as reject] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3301:34)
    at Socket.<anonymous> (/Users/mattlankford/.atom/packages/preview-plus/lib/lang/command.coffee:22:13)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

### Commands

```
     -0:17.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "mobile-preview",
      "racer",
      "rails-snippets",
      "aligner-ruby",
      "refactor",
      "emmet",
      "seeing-is-believing",
      "platformio-ide",
      "particle-dev",
      "platformio-ide-terminal",
      "platomformio",
      "console-panel",
      "atom-refactoring-tools",
      "rails-partials",
      "w3c-validation"
    ],
    "packagesWithKeymapsDisabled": []
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
aligner, v0.22.0
atom-html-preview, v0.1.19
autocomplete-clang, v0.9.3
autocomplete-ruby, v0.1.0
build, v0.62.0
build-cargo, v0.15.0
data-atom, v0.20.3
environment, v1.2.0
git-hide, v0.1.2
hashrocket, v0.4.10
html2haml, v0.10.0
language-crystal-actual, v0.28.2
language-haml, v0.24.0
language-ini, v1.16.0
linter, v1.11.4
linter-crystal, v3.2.4
linter-gcc, v0.6.14
linter-haml, v1.2.0
minimap, v4.23.5
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.1
minimap-pigments, v0.2.0
preview-plus, v1.2.6
ruby-syntax-replacer, v0.5.1
sync-settings, v0.7.2
terminal-plus, v0.14.5
tool-bar, v0.4.0
tree-ignore, v0.6.1

# Dev
No dev packages
```

**Comment by lankford** [comment]
Github will not let me add the HTML file, but it was the index (a long one) from some template I found...

Probly needs a string.scrub ?

m

**Comment by skandasoft** [comment]
Please check the latest patch and feel free to reopen if the issue still exit
