### ISSUE TITLE
Doesn't load on OS X

### ISSUE THREAD

**Issue by wmertens** [skandasoft/preview-plus#9]
Tried installing on OS X 10.10 with Atom 0.179.

It can't find event-kit. I tried installing Atom from scratch, running npm update in the package directory, to no avail.

```
 Failed to load package named 'preview-plus' Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/wmertens/.atom/packages/preview-plus/lib/watch.coffee:2:13)
  at Object.<anonymous> (/Users/wmertens/.atom/packages/preview-plus/lib/watch.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript [as .coffee] (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:74:19)
  at Module.load (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/wmertens/.atom/packages/preview-plus/lib/preview-plus.coffee:10:9)
  at Object.<anonymous> (/Users/wmertens/.atom/packages/preview-plus/lib/preview-plus.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript [as .coffee] (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:74:19)
  at Module.load (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/package.js:651:34)
  at /Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/package.js:190:28
  at Package.module.exports.Package.measure (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:378:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:355:14)
  at Atom.module.exports.Atom.startEditorWindow (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/atom.js:607:21)
  at Object.<anonymous> (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (/Users/wmertens/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at window.onload (file:///Users/wmertens/Applications/Atom.app/Contents/Resources/app/static/index.js:74:25)
```

**Comment by olmokramer** [comment]
Same here on Linux.

@wmertens , you can fix this by running `apm install --save event-kit` from the `~/.atom/packages/preview-plus/` directory

**Comment by skandasoft** [comment]
The latest patch might help. Please open the issue if it still exists.
